/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee.Regulatory;

import business.Customer.Customer;
import business.Employee.Employee;
import business.Enterprise.Enterprise;
import business.Investment.Investment;
import business.WorkQueue.GovernmentWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vrushali Shah
 */
public class AccumulateDataJPanel extends javax.swing.JPanel {

    private JPanel provideDataContainer;
    private Enterprise enterprise;
    private GovernmentWorkRequest gwr;
    private List<Investment> toSend;

    /**
     * Creates new form ServeCustomerJPanel
     */
    public AccumulateDataJPanel(JPanel provideDataContainer, GovernmentWorkRequest gwr, Enterprise enterprise) {
        initComponents();
        this.provideDataContainer = provideDataContainer;
        this.gwr = gwr;
        this.enterprise = enterprise;
        toSend = new ArrayList<>();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGovernmentRqst = new javax.swing.JTable();
        btnSendData = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblGovernmentRqst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Investment ID", "Employee ID", "Total Amount", "Date Invested"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGovernmentRqst.setRowHeight(20);
        jScrollPane1.setViewportView(tblGovernmentRqst);

        btnSendData.setBackground(new java.awt.Color(0, 153, 153));
        btnSendData.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSendData.setForeground(new java.awt.Color(255, 255, 255));
        btnSendData.setText("Send Data");
        btnSendData.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSendData.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSendData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendDataActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSendData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(416, 416, 416))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        Customer customer = gwr.getCustomer();
        DefaultTableModel model = (DefaultTableModel) tblGovernmentRqst.getModel();

        model.setRowCount(0);
        for (Employee e : enterprise.getEmployeeDirectory().getEmployeeList()) {
            for (Investment invested : e.getInvestmentList()) {
                if (invested.getCustomer().equals( customer)) {
                    Object[] row = new Object[4];
                    row[0] = invested;
                    row[1] = e;
                    row[2] = invested.totalInvestment();
                    row[3] = new SimpleDateFormat("yyyy-MM-dd").format(invested.getDate());
                    model.addRow(row);
                    
                    toSend.add(invested);
                }
            }

        }
    }

    private void btnSendDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendDataActionPerformed

        gwr.getEnterpriseInvestMap().put(enterprise, toSend);
        JOptionPane.showMessageDialog(null, "Data has been sent to the Government", "Info", JOptionPane.INFORMATION_MESSAGE);
    
        goBack();
    }//GEN-LAST:event_btnSendDataActionPerformed

    private void goBack() {
        provideDataContainer.remove(this);
        ProvideDataJPanel pd;
        pd = (ProvideDataJPanel) provideDataContainer.getComponent(provideDataContainer.getComponentCount() - 1);
        pd.populateTable();
        CardLayout layout = (CardLayout) provideDataContainer.getLayout();
        layout.previous(provideDataContainer);
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGovernmentRqst;
    // End of variables declaration//GEN-END:variables
}
