/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee.Regulatory;

import business.Customer.Customer;
import business.Employee.Employee;
import business.Enterprise.Enterprise;
import business.Organisation.Organisation;
import business.Organisation.RegulatroyOrganization;
import business.Useraccount.UserAccount;
import business.WorkQueue.GovernmentWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vrushali Shah
 */
public class ProvideDataJPanel extends javax.swing.JPanel {

    private JPanel provideDataContainer;
    private Enterprise enterprise;
    private UserAccount account;

    /**
     * Creates new form ServeCustomerJPanel
     */
    public ProvideDataJPanel(JPanel provideDataContainer, Organisation organisation, UserAccount account) {
        initComponents();
        this.provideDataContainer = provideDataContainer;
        enterprise = organisation.getInEnterprise();
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGovernmentRqst = new javax.swing.JTable();
        btnServeCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblGovernmentRqst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "RequestId", "Government ID", "CustomerID", "Request Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGovernmentRqst.setRowHeight(20);
        jScrollPane1.setViewportView(tblGovernmentRqst);

        btnServeCustomer.setBackground(new java.awt.Color(0, 153, 153));
        btnServeCustomer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnServeCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomer.setText("Send Data");
        btnServeCustomer.setMaximumSize(new java.awt.Dimension(200, 200));
        btnServeCustomer.setMinimumSize(new java.awt.Dimension(200, 200));
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblGovernmentRqst.getModel();

         Organisation found = null;
        for (Organisation o : enterprise.getOrganisationDirectory().getOrganisationList()) {
            if (o instanceof RegulatroyOrganization) {
                found = o;
                break;
            }
        }
        model.setRowCount(0);
        for (WorkRequest wr : found.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof GovernmentWorkRequest && !wr.getStatus().equalsIgnoreCase("Completed")){

                GovernmentWorkRequest gwr = (GovernmentWorkRequest) wr;
                if (gwr.getEnterpriseInvestMap().get(enterprise) == null) {
                    Object[] row = new Object[5];
                    row[0] = gwr.getStatus();
                    row[1] = gwr;
                    row[2] = (Employee) gwr.getSender().getPerson();
                    row[3] = (Customer) gwr.getCustomer();
                    row[4] = new SimpleDateFormat("yyyy-MM-dd").format(gwr.getRequestDate());
                   
                    model.addRow(row);
                }
            }
        }
    }

    private void btnServeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerActionPerformed

        int selectedRow = tblGovernmentRqst.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            GovernmentWorkRequest gwr = (GovernmentWorkRequest) tblGovernmentRqst.getValueAt(selectedRow, 1);
            AccumulateDataJPanel panel = new AccumulateDataJPanel(provideDataContainer, gwr, enterprise);
            provideDataContainer.add("TotalCustomerInvestmentJPanel", panel);
            CardLayout cardLayout = (CardLayout) provideDataContainer.getLayout();
            cardLayout.next(provideDataContainer);

        }

    }//GEN-LAST:event_btnServeCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGovernmentRqst;
    // End of variables declaration//GEN-END:variables
}
