/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government;

import business.Customer.CustomerDirectory;
import business.EcoSystem;
import business.Organisation.Organisation;
import business.Useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Vrushali Shah
 */
public class GovermentWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Object object;
    private EcoSystem ecosystem;
    private Organisation organisation;

    /**
     * Creates new form GovermentWorkAreaPanel
     */
    public GovermentWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organisation organisation, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.object = object;
        this.ecosystem = ecosystem;
        this.organisation = organisation;
        loadPanelForRequestCustomerData();
        loadPanelForViewCustomerHistory();

        expertJPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                JTabbedPane sourceTabbedPane = (JTabbedPane) e.getSource();
                int index = sourceTabbedPane.getSelectedIndex();
                if (index == 1) {
                    ViewCustomerHistoryJPanel fi = (ViewCustomerHistoryJPanel) viewCustomerHistoryContainer.getComponent(0);
                    fi.populateTable();
                }
            }
        });

       lblDisplayImg.setIcon(account.getPerson().getImgIcon());
        txtLoginName.setText(account.getPerson().getFirstName() + " " + account.getPerson().getLastName());

    }

    private void loadPanelForRequestCustomerData() {
        CustomerDirectory customerDir = ecosystem.getCustomerDirectory();
        RequestCustomerDataJPanel panel = new RequestCustomerDataJPanel(requestCustomerContainer, customerDir, organisation, account, ecosystem);
        requestCustomerContainer.add("RequestCustomerDataJPanel", panel);
        CardLayout cardLayout = (CardLayout) requestCustomerContainer.getLayout();
        cardLayout.next(requestCustomerContainer);
    }

    private void loadPanelForViewCustomerHistory() {
        CustomerDirectory customerDir = ecosystem.getCustomerDirectory();
        ViewCustomerHistoryJPanel panel = new ViewCustomerHistoryJPanel(viewCustomerHistoryContainer, customerDir, organisation, account, ecosystem);
        viewCustomerHistoryContainer.add("ViewCustomerHistoryJPanel", panel);
        CardLayout cardLayout = (CardLayout) viewCustomerHistoryContainer.getLayout();
        cardLayout.next(viewCustomerHistoryContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        expertJPanel = new javax.swing.JTabbedPane();
        requestCustomerContainer = new javax.swing.JPanel();
        viewCustomerHistoryContainer = new javax.swing.JPanel();
        lblDisplayImg = new javax.swing.JLabel();
        lblManagername1 = new javax.swing.JLabel();
        txtLoginName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Global Stock Investments Console");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Government Employee WorkArea");

        expertJPanel.setBackground(new java.awt.Color(255, 255, 255));

        requestCustomerContainer.setBackground(new java.awt.Color(255, 255, 255));
        requestCustomerContainer.setLayout(new java.awt.CardLayout());
        expertJPanel.addTab("Request Customer Data", requestCustomerContainer);

        viewCustomerHistoryContainer.setBackground(new java.awt.Color(255, 255, 255));
        viewCustomerHistoryContainer.setLayout(new java.awt.CardLayout());
        expertJPanel.addTab("View History", viewCustomerHistoryContainer);

        lblDisplayImg.setText("<Image>");
        lblDisplayImg.setToolTipText("Image");

        lblManagername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManagername1.setForeground(new java.awt.Color(0, 102, 0));
        lblManagername1.setText("Government Employee");

        txtLoginName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLoginName.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomername1)))
                .addGap(413, 413, 413)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblManagername1)
                        .addGap(36, 36, 36))
                    .addComponent(txtLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(expertJPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblCustomername1)))
                            .addComponent(lblDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManagername1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expertJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane expertJPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblDisplayImg;
    private javax.swing.JLabel lblManagername1;
    private javax.swing.JPanel requestCustomerContainer;
    private javax.swing.JLabel txtLoginName;
    private javax.swing.JPanel viewCustomerHistoryContainer;
    // End of variables declaration//GEN-END:variables
}
