/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government;

import business.Customer.Customer;
import business.Customer.CustomerDirectory;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.FinancialEnterprise;
import business.Network.Network;
import business.Organisation.GovernmentOrganization;
import business.Organisation.Organisation;
import business.Organisation.RegulatroyOrganization;
import business.Useraccount.UserAccount;
import business.WorkQueue.GovernmentWorkRequest;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vrushali Shah
 */
public class RequestCustomerDataJPanel extends javax.swing.JPanel {

    private JPanel requestCustomerContainer;
    private CustomerDirectory customerDir;
    private Organisation organisation;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem ecosystem;

    /**
     * Creates new form RequestCustomerDataJPanel
     */
    public RequestCustomerDataJPanel(JPanel requestCustomerContainer, CustomerDirectory customerDir, Organisation organisation, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.requestCustomerContainer = requestCustomerContainer;
        this.customerDir = customerDir;
        this.organisation = organisation;
        this.account = account;
        this.ecosystem = ecosystem;
        enterprise = organisation.getInEnterprise();
        network = enterprise.getInNetwork();

        editable(false);

        comboCustomer.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                populateFields((Customer) comboCustomer.getSelectedItem());

            }
        });
        populateComboCustomer();
        comboCustomer.setSelectedItem(0);

    }

    private void populateFields(Customer customer) {

        editable(false);

        txtID.setText(String.valueOf(customer.getId()));
        txtFirstName.setText(customer.getFirstName());
        txtLastname.setText(customer.getLastName());
        txtMobile.setText(String.valueOf(customer.getMobileNumber()));
        txtSex.setText(customer.getSex());
        txtAge.setText(String.valueOf(customer.getAge()));

    }

    private void populateComboCustomer() {
        for (Customer c : customerDir.getCustomerList()) {
            comboCustomer.addItem(c);
        }
    }

    private void editable(boolean state) {
        txtID.setEditable(state);
        txtFirstName.setEditable(state);
        txtLastname.setEditable(state);
        txtMobile.setEditable(state);
        txtAge.setEditable(state);
        txtSex.setEditable(state);

    }

    private void clear() {

        txtID.setText("");
        txtFirstName.setText("");
        txtLastname.setText("");
        txtMobile.setText("");
        txtSex.setText("");
        txtAge.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        comboCustomer = new javax.swing.JComboBox();
        btnRequestData = new javax.swing.JButton();
        lblCustId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblFname = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("Customer");

        btnRequestData.setBackground(new java.awt.Color(0, 153, 153));
        btnRequestData.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRequestData.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestData.setText("Request Data");
        btnRequestData.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRequestData.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRequestData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDataActionPerformed(evt);
            }
        });

        lblCustId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustId.setForeground(new java.awt.Color(255, 153, 0));
        lblCustId.setText("Customer ID:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblFname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFname.setForeground(new java.awt.Color(255, 153, 0));
        lblFname.setText("FirstName");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
        });

        lblLname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblLname.setForeground(new java.awt.Color(255, 153, 0));
        lblLname.setText("LastName");

        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });
        txtLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastnameKeyPressed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 153, 0));
        lblAge.setText("Age");

        lblSex.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSex.setForeground(new java.awt.Color(255, 153, 0));
        lblSex.setText("Sex");

        lblMobile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMobile.setForeground(new java.awt.Color(255, 153, 0));
        lblMobile.setText("Mobile Number");

        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileKeyPressed(evt);
            }
        });

        txtSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexActionPerformed(evt);
            }
        });
        txtSex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSexKeyPressed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRequestData, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLname)
                                .addGap(18, 18, 18)
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFname)
                                .addGap(18, 18, 18)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustId)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMobile)
                                .addGap(18, 18, 18)
                                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAge)
                                    .addComponent(lblSex))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustId)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSex)
                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobile)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(btnRequestData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDataActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(comboCustomer.getSelectedItem()).equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select the customer to request its data!");
        } else {

            Customer customer = (Customer) comboCustomer.getSelectedItem();

            GovernmentWorkRequest gwr = new GovernmentWorkRequest();
            gwr.setCustomer(customer);
            gwr.setStatus("Processing");
            gwr.setSender(account);

            //Government Org Work Queue
            for (Organisation org : enterprise.getOrganisationDirectory().getOrganisationList()) {
                if (org instanceof GovernmentOrganization) {
                    org.getWorkQueue().getWorkRequestList().add(gwr);
                }
            }

            //Regulatory Org workQueue
            for (Network n : ecosystem.getNetworkDirectory().getNetworkList()) {
                if (n.equals(network)) {
                    for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e instanceof FinancialEnterprise) {
                            for (Organisation o : e.getOrganisationDirectory().getOrganisationList()) {
                                if (o instanceof RegulatroyOrganization) {
                                    o.getWorkQueue().getWorkRequestList().add(gwr);
                                }
                            }
                        }
                    }
                }
            }// end of for
            JOptionPane.showMessageDialog(null, "Customer data requested successfully!");
            clear();
        }

    }//GEN-LAST:event_btnRequestDataActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtFirstName.setEditable(false);
            txtFirstName.setBackground(Color.red);
        } else {
            txtFirstName.setEditable(true);
            txtFirstName.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtLastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtLastname.setEditable(false);
            txtLastname.setBackground(Color.red);
        } else {
            txtLastname.setEditable(true);
            txtLastname.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_txtLastnameKeyPressed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)
                || (key == evt.VK_BACK_SPACE || key == evt.VK_DELETE)) {
            txtMobile.setEditable(true);
            txtMobile.setBackground(Color.WHITE);
        } else {

            txtMobile.setEditable(false);
            txtMobile.setBackground(Color.red);

        }
    }//GEN-LAST:event_txtMobileKeyPressed

    private void txtSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexActionPerformed

    private void txtSexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSexKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexKeyPressed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestData;
    private javax.swing.JComboBox comboCustomer;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblSex;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtSex;
    // End of variables declaration//GEN-END:variables
}
