/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government;

import business.Customer.CustomerDirectory;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Organisation.GovernmentOrganization;
import business.Organisation.Organisation;
import business.Useraccount.UserAccount;
import business.WorkQueue.GovernmentWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vrushali Shah
 */
public class ViewCustomerHistoryJPanel extends javax.swing.JPanel {

    private JPanel viewCustomerHistoryContainer;
    private CustomerDirectory customerDir;
    private Organisation organisation;
    private UserAccount account;
    private EcoSystem ecosystem;
    private Enterprise enterprise;

    /**
     * Creates new form ViewCustomerHistoryJPanel
     */
    public ViewCustomerHistoryJPanel(JPanel viewCustomerHistoryContainer, CustomerDirectory customerDir, Organisation organisation, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.viewCustomerHistoryContainer = viewCustomerHistoryContainer;
        this.customerDir = customerDir;
        this.organisation = organisation;
        this.account = account;
        this.ecosystem = ecosystem;
        enterprise = organisation.getInEnterprise();
        populateTable();
    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblCustomerData.getModel();
        model.setRowCount(0);
          SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        for (Organisation org : enterprise.getOrganisationDirectory().getOrganisationList()) {
            if (org instanceof GovernmentOrganization) {
                for (WorkRequest wr : org.getWorkQueue().getWorkRequestList()) {
                    if (wr instanceof GovernmentWorkRequest) {
                        GovernmentWorkRequest gwr = (GovernmentWorkRequest) wr;
                        Object[] row = new Object[5];
                        row[0] = gwr;
                        row[1] = gwr.getCustomer().getId();
                        row[2] = formatter.format(gwr.getRequestDate());
                        row[3] = gwr.getResolveDate()!=null?formatter.format(gwr.getResolveDate()):"";
                        row[4] = gwr.getStatus();
                        model.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerData = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCustomerData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestId", "CustomerId", "Request Date", "Resolve Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerData);

        btnViewDetails.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDetails.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("View Details");
        btnViewDetails.setMaximumSize(new java.awt.Dimension(200, 200));
        btnViewDetails.setMinimumSize(new java.awt.Dimension(200, 200));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(687, 687, 687))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomerData.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            GovernmentWorkRequest gwr = (GovernmentWorkRequest) tblCustomerData.getValueAt(selectedRow, 0);
            ViewCustomerDetailsJPanel panel = new ViewCustomerDetailsJPanel(viewCustomerHistoryContainer, gwr);
            viewCustomerHistoryContainer.add("ViewCustomerDetailsJPanel", panel);
            CardLayout cardLayout = (CardLayout) viewCustomerHistoryContainer.getLayout();
            cardLayout.next(viewCustomerHistoryContainer);

        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomerData;
    // End of variables declaration//GEN-END:variables
}
