/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import business.EcoSystem;
import business.Useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Vrushali Shah
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Object object;
    private EcoSystem ecosystem;

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Object object, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.object = object;
        this.ecosystem = ecosystem;
        loadAdvicePanel();
        loadFuturePanel();
        loadViewReqPanel();
        loadHistoryPanel();
        loadSessionPanel();
        loadSellPanel();
        loadStockHistory();
        customerJPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                JTabbedPane sourceTabbedPane = (JTabbedPane) e.getSource();
                int index = sourceTabbedPane.getSelectedIndex();
                if (index == 1) {
                    FuturInvestmentJPanel fi = (FuturInvestmentJPanel) futureInvContainer.getComponent(0);
                    fi.populateTable();
                }
                if (index == 2) {
                    ViewRequestsJPanel vr = (ViewRequestsJPanel) viewRequestContainer.getComponent(0);
                    vr.networkCombo.setSelectedIndex(2);
                }
            }
        });
        lblDisplayImg.setIcon(account.getPerson().getImgIcon());
        txtLoginName.setText(account.getPerson().getFirstName() + " " + account.getPerson().getLastName());

    }

    private void loadAdvicePanel() {

        RequestAdviceJPanel panel = new RequestAdviceJPanel(adviceContainer, ecosystem, account);
        adviceContainer.add("RequestAdviceJPanel", panel);
        CardLayout cardLayout = (CardLayout) adviceContainer.getLayout();
        cardLayout.next(adviceContainer);
    }

    private void loadFuturePanel() {

        FuturInvestmentJPanel panel = new FuturInvestmentJPanel(futureInvContainer, ecosystem, account);
        futureInvContainer.add("FuturInvestmentJPanel", panel);
        CardLayout cardLayout = (CardLayout) futureInvContainer.getLayout();
        cardLayout.next(futureInvContainer);
    }

    private void loadViewReqPanel() {

        ViewRequestsJPanel panel = new ViewRequestsJPanel(viewRequestContainer, ecosystem, account);
        viewRequestContainer.add("ViewInvestmentJPanel", panel);
        CardLayout cardLayout = (CardLayout) viewRequestContainer.getLayout();
        cardLayout.next(viewRequestContainer);
    }

    private void loadHistoryPanel() {

        ViewHistoryJPanel panel = new ViewHistoryJPanel(viewHistoryContainer, ecosystem, account);
        viewHistoryContainer.add("ViewHistoryJPanel", panel);
        CardLayout cardLayout = (CardLayout) viewHistoryContainer.getLayout();
        cardLayout.next(viewHistoryContainer);
    }

    private void loadSessionPanel() {

        SpeakerSessionJPanel panel = new SpeakerSessionJPanel(speakerContainer, ecosystem, account);
        speakerContainer.add("SpeakerSessionJPanel", panel);
        CardLayout cardLayout = (CardLayout) speakerContainer.getLayout();
        cardLayout.next(speakerContainer);
    }

    private void loadSellPanel() {

        SellInvestmentJPanel panel = new SellInvestmentJPanel(speakerContainer, ecosystem, account);
        sellContainer.add("SellInvestmentJPanel", panel);
        CardLayout cardLayout = (CardLayout) sellContainer.getLayout();
        cardLayout.next(sellContainer);
    }

    private void loadStockHistory() {

        StockHistoryJPanel panel = new StockHistoryJPanel(stockHistoryContainer, ecosystem);
        stockHistoryContainer.add("StockSelectionJPanel", panel);
        CardLayout cardLayout = (CardLayout) stockHistoryContainer.getLayout();
        cardLayout.next(stockHistoryContainer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        customerJPanel = new javax.swing.JTabbedPane();
        adviceContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        futureInvContainer = new javax.swing.JPanel();
        viewRequestContainer = new javax.swing.JPanel();
        speakerContainer = new javax.swing.JPanel();
        sellContainer = new javax.swing.JPanel();
        stockHistoryContainer = new javax.swing.JPanel();
        viewHistoryContainer = new javax.swing.JPanel();
        lblManagername = new javax.swing.JLabel();
        txtLoginName = new javax.swing.JLabel();
        lblDisplayImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Global Stock Investments Console");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Customer WorkArea");

        customerJPanel.setBackground(new java.awt.Color(255, 255, 255));

        adviceContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        adviceContainer.add(jPanel1, "card2");

        customerJPanel.addTab("Employee Investment Advice", adviceContainer);

        futureInvContainer.setBackground(new java.awt.Color(255, 255, 255));
        futureInvContainer.setLayout(new java.awt.CardLayout());
        customerJPanel.addTab("Future Investments", futureInvContainer);

        viewRequestContainer.setBackground(new java.awt.Color(255, 255, 255));
        viewRequestContainer.setLayout(new java.awt.CardLayout());
        customerJPanel.addTab("View Requests", viewRequestContainer);

        speakerContainer.setBackground(new java.awt.Color(255, 255, 255));
        speakerContainer.setLayout(new java.awt.CardLayout());
        customerJPanel.addTab("Register for Expert Session", speakerContainer);

        sellContainer.setBackground(new java.awt.Color(255, 255, 255));
        sellContainer.setLayout(new java.awt.CardLayout());
        customerJPanel.addTab("Sell Stock", sellContainer);

        stockHistoryContainer.setBackground(new java.awt.Color(255, 255, 255));
        stockHistoryContainer.setLayout(new java.awt.CardLayout());
        customerJPanel.addTab("Stock History", stockHistoryContainer);

        viewHistoryContainer.setBackground(new java.awt.Color(255, 255, 255));
        viewHistoryContainer.setLayout(new java.awt.CardLayout());
        customerJPanel.addTab("View History", viewHistoryContainer);

        lblManagername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManagername.setForeground(new java.awt.Color(0, 102, 0));
        lblManagername.setText("Customer");

        txtLoginName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLoginName.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomername1)))
                .addGap(408, 408, 408)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManagername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addComponent(customerJPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblCustomername1)))
                            .addComponent(lblDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblManagername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerJPanel))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adviceContainer;
    private javax.swing.JTabbedPane customerJPanel;
    private javax.swing.JPanel futureInvContainer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblDisplayImg;
    private javax.swing.JLabel lblManagername;
    private javax.swing.JPanel sellContainer;
    private javax.swing.JPanel speakerContainer;
    private javax.swing.JPanel stockHistoryContainer;
    private javax.swing.JLabel txtLoginName;
    private javax.swing.JPanel viewHistoryContainer;
    private javax.swing.JPanel viewRequestContainer;
    // End of variables declaration//GEN-END:variables
}
