/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import business.Customer.Customer;
import business.Customer.StockDetails;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.FinancialEnterprise;
import business.Investment.InvestmentItem;
import business.Network.Network;
import business.Organisation.InvestmentAndRiskOrganization;
import business.Organisation.Organisation;
import business.Stock.Stock;
import business.Useraccount.UserAccount;
import business.Utilities;
import business.WorkQueue.InvestmentWorkRequest;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Map;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Prashant Kabra (kabra.p@husky.neu.edu)
 */
public class SellInvestmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FuturInvestmentJPanel
     */
    private UserAccount account;
    private EcoSystem ecosystem;
    private JPanel sellContainer;
    private Customer customer;
    DefaultTableModel model;

    public SellInvestmentJPanel(JPanel sellContainer, EcoSystem ecosystem, UserAccount account) {
        initComponents();
        this.sellContainer = sellContainer;
        this.account = account;
        this.ecosystem = ecosystem;
        this.customer = (Customer) account.getPerson();
        model = (DefaultTableModel) tblSell.getModel();

        TableColumnModel tcm = tblSell.getColumnModel();
        tcm.getColumn(6).setCellEditor(new DefaultCellEditor(Utilities.createFormattedTextField()));
        populateTable();
    
        networkCombo.setEditable(false);
        enterpriseCombo.setEditable(false);

        networkCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                populateEnterpriseCombo((Network) networkCombo.getSelectedItem());

            }
        });
            populateNetworkCombo();
        networkCombo.setSelectedIndex(0);
      model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblSell.getModel();

        model.setRowCount(0);

        for (Map.Entry<Stock, StockDetails> entry : customer.getStockDetailMap().entrySet()) {

            Object[] row = new Object[7];
            Stock s = entry.getKey();
            row[0] = s.getStockId();
            row[1] = s;
            row[2] = s.getNetwork();
            double price = s.getStockHistoryList().get(0).getPrice();

            row[3] = price;
            row[4] = entry.getValue().getRunningTotal();
            row[5] = entry.getValue().getQuantity();
            row[6] = "0";
            model.addRow(row);
            
        }

    }

    private void populateNetworkCombo() {
        for (Network n : ecosystem.getNetworkDirectory().getNetworkList()) {
            networkCombo.addItem(n);
        }
    }

    private void populateEnterpriseCombo(Network n) {
        enterpriseCombo.removeAllItems();
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof FinancialEnterprise) {
                enterpriseCombo.addItem(e);
            }
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        networkCombo = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        enterpriseCombo = new javax.swing.JComboBox<>();
        btnRequestInvestment = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSell = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 0));
        jLabel26.setText("Networks");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 0));
        jLabel27.setText("Enterprise");

        btnRequestInvestment.setBackground(new java.awt.Color(0, 153, 153));
        btnRequestInvestment.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRequestInvestment.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestInvestment.setText("Request Investment");
        btnRequestInvestment.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRequestInvestment.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRequestInvestment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestInvestmentActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 0));
        jLabel25.setText("Sell Stock Items");

        tblSell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StockId", "StockName", "Network", "Current Price", "Running Total", "Owned", "Sell Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSell.setRowHeight(20);
        jScrollPane4.setViewportView(tblSell);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(networkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRequestInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkCombo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRequestInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestInvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestInvestmentActionPerformed
        // TODO add your handling code here:
        if (areQuantityFine()) {
            Customer c = (Customer) account.getPerson();
            InvestmentWorkRequest iwr = new InvestmentWorkRequest(1);
            iwr.setStatus("Requested");
            Enterprise e = (Enterprise) enterpriseCombo.getSelectedItem();
            c.getWorkQueue().addWorkRequest(iwr);
            for (Organisation o : e.getOrganisationDirectory().getOrganisationList()) {
                if (o instanceof InvestmentAndRiskOrganization) {
                    o.getWorkQueue().getWorkRequestList().add(iwr);
                    iwr.setOrganisation(o);
                }
            }

            for (int i = 0; i < tblSell.getRowCount(); i++) {
                if (tblSell.getValueAt(i, 6) != null) {
                    Integer value=Integer.parseInt((String) tblSell.getValueAt(i, 6));
                  
                        if(value!=0){
                        InvestmentItem item = new InvestmentItem();
                        item.setStock((Stock) tblSell.getValueAt(i, 1));
                        item.setQuantity(value);
                        iwr.getInvestment().addInvestmentItem(item);
                    }
                }
            }
JOptionPane.showMessageDialog(null, "Request has been sent", "Warning", JOptionPane.WARNING_MESSAGE);
     
        } else {
            JOptionPane.showMessageDialog(null, "Cant sell more than you have", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnRequestInvestmentActionPerformed

    private boolean areQuantityFine() {
        for (int i = 0; i < tblSell.getRowCount(); i++) {
                if (String.valueOf(tblSell.getValueAt(i, 6)).trim().isEmpty()) {
                return false;
                }
                else{
                    int owned =Integer.parseInt((String) tblSell.getValueAt(i, 5));
                    int toSell = Integer.parseInt((String) tblSell.getValueAt(i, 6));
                    if (toSell > owned || toSell <0) {
                        return false;
                    }
                }
            
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestInvestment;
    private javax.swing.JComboBox<Enterprise> enterpriseCombo;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<Network> networkCombo;
    private javax.swing.JTable tblSell;
    // End of variables declaration//GEN-END:variables
}
