/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import business.Customer.Customer;
import business.EcoSystem;
import business.Expert.SpeakerSession;
import business.Network.Network;
import business.Useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prashant Kabra (kabra.p@husky.neu.edu)
 */
public class SpeakerSessionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SpeakerSessionJPanel
     */
    private JPanel speakerContainer;
    private EcoSystem ecosystem;
    private UserAccount account;
    private Customer c;
    public SpeakerSessionJPanel(JPanel speakerContainer, EcoSystem ecosystem, UserAccount account) {
        initComponents();
        this.speakerContainer = speakerContainer;
        this.ecosystem = ecosystem;
        this.account = account;
       
        c = (Customer) account.getPerson();
        networkCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                populateTable((Network) networkCombo.getSelectedItem());

            }
        });
         populateNetworkCombo();
        networkCombo.setSelectedIndex(0);
    }

    public void populateTable(Network n) {
        DefaultTableModel model = (DefaultTableModel) tblSpeakerSessions.getModel();

        model.setRowCount(0);
        Customer c = (Customer) account.getPerson();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        for (SpeakerSession session : n.getSpeakerSessionList()) {
            Object[] row = new Object[7];

            row[0] = session;
            row[1] = formatter.format(session.getDate());
            row[2] = session.getStartTime();
            row[3] = session.getEndTime();
            row[4] = session.getSpeaker().getFirstName() + " " + session.getSpeaker().getLastName();
            row[5] = session.getStatus();
            row[6] = session.getRegisteredCustomerList().contains(c) ? "Yes" : "No";
            model.addRow(row);
        }

    }

    private void populateNetworkCombo() {
        for (Network n : ecosystem.getNetworkDirectory().getNetworkList()) {
            networkCombo.addItem(n);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelExpSession = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        networkCombo = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSpeakerSessions = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCancelExpSession.setBackground(new java.awt.Color(0, 153, 153));
        btnCancelExpSession.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCancelExpSession.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelExpSession.setText("Cancel");
        btnCancelExpSession.setMaximumSize(new java.awt.Dimension(200, 200));
        btnCancelExpSession.setMinimumSize(new java.awt.Dimension(200, 200));
        btnCancelExpSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelExpSessionActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 153, 153));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("View Details");
        btnRegister.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRegister.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 0));
        jLabel18.setText("Networks");

        tblSpeakerSessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Session ID", "Session Date", "Start Time", "End Time", "Speaker", "Session Status", "Registered"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSpeakerSessions.setRowHeight(20);
        jScrollPane4.setViewportView(tblSpeakerSessions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(networkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCancelExpSession, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(networkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelExpSession, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelExpSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelExpSessionActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSpeakerSessions.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a session first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String status=(String) tblSpeakerSessions.getValueAt(selectedRow, 6);
            if(status.equalsIgnoreCase("no")){
        JOptionPane.showMessageDialog(null, "You are not registered for this session", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
            SpeakerSession session = (SpeakerSession) tblSpeakerSessions.getValueAt(selectedRow, 0);

            session.getRegisteredCustomerList().remove(c);
            c.getRegisteredSessionsList().remove(session);
            }
        }
    }//GEN-LAST:event_btnCancelExpSessionActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSpeakerSessions.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a session first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            SpeakerSession session = (SpeakerSession) tblSpeakerSessions.getValueAt(selectedRow, 0);

            SpeakerSessionDetailsJPanel speakerSessionDetailsJPanel = new SpeakerSessionDetailsJPanel(speakerContainer, session, account);
            speakerContainer.add("SpeakerSessionDetailsJPanel", speakerSessionDetailsJPanel);
            CardLayout layout = (CardLayout) speakerContainer.getLayout();
            layout.next(speakerContainer);

        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelExpSession;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JComboBox<Network> networkCombo;
    private javax.swing.JTable tblSpeakerSessions;
    // End of variables declaration//GEN-END:variables
}
