/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import business.Customer.Customer;
import business.Expert.SpeakerSession;
import business.Useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;

/**
 *
 * @author Prashant Kabra (kabra.p@husky.neu.edu)
 */
public class SpeakerSessionDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterSpeakerSessionJPanel
     */
    private JPanel speakerContainer;
    private SpeakerSession session;
    private UserAccount account;
    private boolean isRegisterd;

    public SpeakerSessionDetailsJPanel(JPanel speakerContainer, SpeakerSession session, UserAccount account) {
        initComponents();
        this.speakerContainer = speakerContainer;
        this.session = session;
        this.account = account;
        populate();
    }

    private void populate() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        idTxt.setText(session.toString());
        dateTxt.setText(formatter.format(session.getDate()));
        startTimeTxt.setText(session.getStartTime().toString());
        endTimeTxt.setText(session.getEndTime().toString());
        totalSeatsTxt.setText(String.valueOf(session.getCapacity()));
        seatsAvailableTxt.setText(String.valueOf(session.getRemaining()));
        statusTxt.setText(session.getStatus());
        isRegisterd = session.getRegisteredCustomerList().contains((Customer) account.getPerson());

        if (isRegisterd) {
            regStatusTxt.setText("Yes");
            btnRegCan.setText("Cancel");
        } else {
            regStatusTxt.setText("No");
            btnRegCan.setText("Register");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        btnRegCan = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desctxt = new javax.swing.JTextArea();
        totalSeatsTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        seatsAvailableTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        endTimeTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        startTimeTxt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        regStatusTxt = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 0));
        jLabel25.setText("End Time");

        btnRegCan.setBackground(new java.awt.Color(0, 153, 153));
        btnRegCan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRegCan.setForeground(new java.awt.Color(255, 255, 255));
        btnRegCan.setText("Cancel");
        btnRegCan.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRegCan.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRegCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCanActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("Session Date");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 153, 0));
        jLabel23.setText("Start Time");

        desctxt.setEditable(false);
        desctxt.setColumns(20);
        desctxt.setRows(5);
        desctxt.setEnabled(false);
        jScrollPane1.setViewportView(desctxt);

        totalSeatsTxt.setEditable(false);
        totalSeatsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSeatsTxtActionPerformed(evt);
            }
        });
        totalSeatsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalSeatsTxtKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Seats Available");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 153, 0));
        jLabel24.setText("Description");

        seatsAvailableTxt.setEditable(false);
        seatsAvailableTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsAvailableTxtActionPerformed(evt);
            }
        });
        seatsAvailableTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seatsAvailableTxtKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Session Id");

        idTxt.setEditable(false);
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTxtKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 153, 0));
        jLabel22.setText("Status");

        endTimeTxt.setEditable(false);
        endTimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTimeTxtActionPerformed(evt);
            }
        });
        endTimeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                endTimeTxtKeyPressed(evt);
            }
        });

        dateTxt.setEditable(false);
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });
        dateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateTxtKeyPressed(evt);
            }
        });

        startTimeTxt.setEditable(false);
        startTimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeTxtActionPerformed(evt);
            }
        });
        startTimeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                startTimeTxtKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 0));
        jLabel26.setText("Total Seats");

        statusTxt.setEditable(false);
        statusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTxtActionPerformed(evt);
            }
        });
        statusTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusTxtKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 0));
        jLabel27.setText("Registration Status");

        regStatusTxt.setEditable(false);
        regStatusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regStatusTxtActionPerformed(evt);
            }
        });
        regStatusTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regStatusTxtKeyPressed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegCan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(regStatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(97, 97, 97)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel22)))
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatsAvailableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(endTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalSeatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(startTimeTxt)
                                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(startTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalSeatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(seatsAvailableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(regStatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel24)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegCan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCanActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) account.getPerson();
        if (isRegisterd) {
            session.getRegisteredCustomerList().remove(c);
            c.getRegisteredSessionsList().remove(session);
        } else {
            session.getRegisteredCustomerList().add(c);
            c.getRegisteredSessionsList().add(session);
        } 
        Component[] componentArray = speakerContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SpeakerSessionJPanel speakerSessionJPanel = (SpeakerSessionJPanel) component;
        speakerSessionJPanel.networkCombo.setSelectedIndex(0);
        populate();
    }//GEN-LAST:event_btnRegCanActionPerformed

    private void totalSeatsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSeatsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSeatsTxtActionPerformed

    private void totalSeatsTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalSeatsTxtKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_totalSeatsTxtKeyPressed

    private void seatsAvailableTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsAvailableTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsAvailableTxtActionPerformed

    private void seatsAvailableTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsAvailableTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsAvailableTxtKeyPressed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void idTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtKeyPressed

    private void endTimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTimeTxtActionPerformed

    private void endTimeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_endTimeTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTimeTxtKeyPressed

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed

    private void dateTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtKeyPressed

    private void startTimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTimeTxtActionPerformed

    private void startTimeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startTimeTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTimeTxtKeyPressed

    private void statusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTxtActionPerformed

    private void statusTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTxtKeyPressed

    private void regStatusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regStatusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regStatusTxtActionPerformed

    private void regStatusTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regStatusTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_regStatusTxtKeyPressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        speakerContainer.remove(this);
        Component[] componentArray = speakerContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SpeakerSessionJPanel speakerSessionJPanel = (SpeakerSessionJPanel) component;
        speakerSessionJPanel.networkCombo.setSelectedIndex(0);
        CardLayout layout = (CardLayout) speakerContainer.getLayout();
        layout.previous(speakerContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegCan;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextArea desctxt;
    private javax.swing.JTextField endTimeTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField regStatusTxt;
    private javax.swing.JTextField seatsAvailableTxt;
    private javax.swing.JTextField startTimeTxt;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JTextField totalSeatsTxt;
    // End of variables declaration//GEN-END:variables
}
