/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import business.Customer.Customer;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.GovernmentEnterprise;
import business.Network.Network;
import business.Useraccount.UserAccount;
import business.WorkQueue.AdviceWorkRequest;
import business.WorkQueue.InvestmentWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vrushali Shah
 */
public class ViewRequestsJPanel extends javax.swing.JPanel {

    private JPanel viewRequestContainer;
    private UserAccount account;
    private EcoSystem ecosystem;

    /**
     * Creates new form ViewInvestmentRequest
     */
    public ViewRequestsJPanel(JPanel viewRequestContainer, EcoSystem ecosystem, UserAccount account) {
        initComponents();
        this.viewRequestContainer = viewRequestContainer;
        this.account = account;
        this.ecosystem = ecosystem;
       
        networkCombo.setEditable(false);
        enterpriseCombo.setEditable(false);

        networkCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                populateEnterpriseCombo((Network) networkCombo.getSelectedItem());

            }
        });
        enterpriseCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                populateTable((Enterprise) enterpriseCombo.getSelectedItem());

            }
        });
         populateNetworkCombo();
        networkCombo.setSelectedIndex(0);
    }

    private void populateNetworkCombo() {
        for (Network n : ecosystem.getNetworkDirectory().getNetworkList()) {
            networkCombo.addItem(n);
        }
    }

    private void populateEnterpriseCombo(Network n) {
        enterpriseCombo.removeAllItems();
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (!(e instanceof GovernmentEnterprise)) {
                enterpriseCombo.addItem(e);
            }
        }

    }

    public void populateTable(Enterprise e) {
        DefaultTableModel model = (DefaultTableModel) tblRequestedInv.getModel();

        model.setRowCount(0);
        Customer c = (Customer) account.getPerson();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        for (WorkRequest wr : c.getWorkQueue().getWorkRequestList()) {
            try{
            if (wr.getOrganisation().getInEnterprise() == e) {
                Object[] row = new Object[9];
                if (wr instanceof InvestmentWorkRequest) {
                    InvestmentWorkRequest iwr = (InvestmentWorkRequest) wr;
                    row[0] = iwr;
                    row[1] = "InvestmentWorkRequest";
                    row[2] = "NA";
                } else if (wr instanceof AdviceWorkRequest) {
                    AdviceWorkRequest awr = (AdviceWorkRequest) wr;
                    row[0] = awr;
                    row[1] = "AdviceWorkRequest";
                    row[2] = awr.getRisk().name();
                }
                row[3] = wr.getOrganisation().getInEnterprise().getInNetwork();
                row[4] = wr.getOrganisation().getInEnterprise();
                row[5] = wr.getStatus();
                row[6] = formatter.format(wr.getRequestDate());
                row[7] = wr.getResolveDate() != null ? formatter.format(wr.getResolveDate()) : "";
                row[8] = wr.getReceiver() != null ? wr.getReceiver() : "";

                model.addRow(row);
            }
        }
          catch(Exception ex){
                ex.getMessage();
                }
        }
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRequestedInv = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        networkCombo = new javax.swing.JComboBox<>();
        enterpriseCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("Requested Investments");

        tblRequestedInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestId", "Request Type", "Risk", "Network", "Enterprise", "Status", "Request Date", "Resolve Date", "Assigned Employee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequestedInv.setRowHeight(20);
        jScrollPane2.setViewportView(tblRequestedInv);

        btnView.setBackground(new java.awt.Color(0, 153, 153));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.setMaximumSize(new java.awt.Dimension(200, 200));
        btnView.setMinimumSize(new java.awt.Dimension(200, 200));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Enterprise");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Networks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(638, 638, 638)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(networkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequestedInv.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            WorkRequest wr = (WorkRequest) tblRequestedInv.getValueAt(selectedRow, 0);
            if (wr instanceof AdviceWorkRequest) {
                if (wr.getStatus().equalsIgnoreCase("Completed")) {
                    AdviceWorkRequest awr = (AdviceWorkRequest) wr;
                    ViewAdviceRequestJPanel viewAdviceRequestJPanel = new ViewAdviceRequestJPanel(viewRequestContainer, awr);
                    viewRequestContainer.add("ViewAdviceRequestJPanel", viewAdviceRequestJPanel);
                    CardLayout layout = (CardLayout) viewRequestContainer.getLayout();
                    layout.next(viewRequestContainer);
                } else {
                    JOptionPane.showMessageDialog(null, "Request not completed yet.", "Warning", JOptionPane.INFORMATION_MESSAGE);

                }
            } else {

                InvestmentWorkRequest iwr = (InvestmentWorkRequest) wr;
                ViewInvestmentRequestJPanel viewInvestmentRequestJPanel = new ViewInvestmentRequestJPanel(viewRequestContainer, iwr);
                viewRequestContainer.add("ViewInvestmentRequestJPanel", viewInvestmentRequestJPanel);
                CardLayout layout = (CardLayout) viewRequestContainer.getLayout();
                layout.next(viewRequestContainer);
            }
        }
    }//GEN-LAST:event_btnViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<Enterprise> enterpriseCombo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<Network> networkCombo;
    private javax.swing.JTable tblRequestedInv;
    // End of variables declaration//GEN-END:variables
}
