/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee.InvestmentAndRisk;

import business.Customer.CustomerDirectory;
import business.EcoSystem;
import business.Employee.Employee;
import business.Organisation.Organisation;
import business.Useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vrushali Shah
 */
public class InvestmentEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Object object;
    private EcoSystem ecosystem;
    private Organisation organisation;

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public InvestmentEmployeeWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organisation organisation, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.object = object;
        this.ecosystem = ecosystem;
        this.organisation = organisation;
        loadPanelForServeCustomer();
        loadPanelForAdviceCustomer();

        lblDisplayImg.setIcon(account.getPerson().getImgIcon());
        txtLoginName.setText(account.getPerson().getFirstName() + " " + account.getPerson().getLastName());
        Employee e = (Employee) account.getPerson();
        txtLoginName1.setText(String.valueOf(e.getTotalIncentive()));
    }

    private void loadPanelForServeCustomer() {
        CustomerDirectory customerDir = ecosystem.getCustomerDirectory();
        ServeCustomerJPanel panel = new ServeCustomerJPanel(serveCustomerContainer, customerDir, organisation, account);
        serveCustomerContainer.add("ServeCustomerJPanel", panel);
        CardLayout cardLayout = (CardLayout) serveCustomerContainer.getLayout();
        cardLayout.next(serveCustomerContainer);
    }

    private void loadPanelForAdviceCustomer() {
        CustomerDirectory customerDir = ecosystem.getCustomerDirectory();
        AdviceCustomerJPanel panel = new AdviceCustomerJPanel(adviceCustContainer, customerDir, organisation, account);
        adviceCustContainer.add("AdviceCustomerJPanel", panel);
        CardLayout cardLayout = (CardLayout) adviceCustContainer.getLayout();
        cardLayout.next(adviceCustContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        expertJPanel = new javax.swing.JTabbedPane();
        serveCustomerContainer = new javax.swing.JPanel();
        adviceCustContainer = new javax.swing.JPanel();
        lblManagername = new javax.swing.JLabel();
        txtLoginName = new javax.swing.JLabel();
        lblDisplayImg = new javax.swing.JLabel();
        lblManagername1 = new javax.swing.JLabel();
        txtLoginName1 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1165, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Global Stock Investments Console");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Investment Employee WorkArea");

        expertJPanel.setBackground(new java.awt.Color(255, 255, 255));
        expertJPanel.setForeground(new java.awt.Color(51, 153, 0));

        serveCustomerContainer.setBackground(new java.awt.Color(255, 255, 255));
        serveCustomerContainer.setForeground(new java.awt.Color(51, 153, 0));
        serveCustomerContainer.setLayout(new java.awt.CardLayout());
        expertJPanel.addTab("Serve Customer", serveCustomerContainer);

        adviceCustContainer.setBackground(new java.awt.Color(255, 255, 255));
        adviceCustContainer.setForeground(new java.awt.Color(51, 153, 0));
        adviceCustContainer.setLayout(new java.awt.CardLayout());
        expertJPanel.addTab("Advice Customer", adviceCustContainer);

        lblManagername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManagername.setForeground(new java.awt.Color(0, 102, 0));
        lblManagername.setText("Investment Employee");

        txtLoginName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLoginName.setForeground(new java.awt.Color(0, 102, 0));

        lblManagername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManagername1.setForeground(new java.awt.Color(0, 102, 0));
        lblManagername1.setText("Total Incentive");

        txtLoginName1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLoginName1.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expertJPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomername1)
                                .addGap(385, 385, 385))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(182, 182, 182)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManagername1)
                                    .addComponent(txtLoginName1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addGap(56, 56, 56)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManagername)
                            .addComponent(txtLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblCustomername1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManagername)
                            .addComponent(lblDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManagername1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoginName1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(expertJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adviceCustContainer;
    private javax.swing.JTabbedPane expertJPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblDisplayImg;
    private javax.swing.JLabel lblManagername;
    private javax.swing.JLabel lblManagername1;
    private javax.swing.JPanel serveCustomerContainer;
    private javax.swing.JLabel txtLoginName;
    private javax.swing.JLabel txtLoginName1;
    // End of variables declaration//GEN-END:variables
}
