/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee.InvestmentAndRisk;

import business.Customer.Customer;
import business.Customer.CustomerDirectory;
import business.Enterprise.Enterprise;
import business.Organisation.InvestmentAndRiskOrganization;
import business.Organisation.Organisation;
import business.Useraccount.UserAccount;
import business.WorkQueue.InvestmentWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vrushali Shah
 */
public class ServeCustomerJPanel extends javax.swing.JPanel {

    private JPanel serveCustomerContainer;
    private Enterprise enterprise;
    private UserAccount account;

    /**
     * Creates new form ServeCustomerJPanel
     */
    public ServeCustomerJPanel(JPanel serveCustomerContainer, CustomerDirectory customerDir, Organisation organisation, UserAccount account) {
        initComponents();
        this.serveCustomerContainer = serveCustomerContainer;
        enterprise = organisation.getInEnterprise();
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnServeCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestId", "Risk", "CustomerID", "Request Date", "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        btnAssign.setBackground(new java.awt.Color(0, 153, 153));
        btnAssign.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(255, 255, 255));
        btnAssign.setText("Assign to me");
        btnAssign.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAssign.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnServeCustomer.setBackground(new java.awt.Color(0, 153, 153));
        btnServeCustomer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnServeCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomer.setText("Serve Customer");
        btnServeCustomer.setMaximumSize(new java.awt.Dimension(200, 200));
        btnServeCustomer.setMinimumSize(new java.awt.Dimension(200, 200));
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)
                        .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();

        Organisation found = null;
        for (Organisation o : enterprise.getOrganisationDirectory().getOrganisationList()) {
            if (o instanceof InvestmentAndRiskOrganization) {
                found = o;
                break;
            }
        }
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        for (WorkRequest wr : found.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof InvestmentWorkRequest && (wr.getReceiver() == null || wr.getReceiver() == account)) {
                InvestmentWorkRequest iwr = (InvestmentWorkRequest) wr;
                Object[] row = new Object[5];
                row[0] = iwr.getId();
                row[1] = iwr;
                row[2] = (Customer) iwr.getSender().getPerson();
                row[3] = sdf.format(iwr.getRequestDate());
                UserAccount r = iwr.getReceiver();
                row[4] = r != null ? sdf.format(r) : "";

                model.addRow(row);
            }
        }
    }

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomer.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a request first");
        } else {
            InvestmentWorkRequest iwr = (InvestmentWorkRequest) tblCustomer.getValueAt(selectedRow, 1);
            iwr.setReceiver(account);
            JOptionPane.showMessageDialog(null, "Request assigned successfully");
            populateTable();
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnServeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerActionPerformed

        int selectedRow = tblCustomer.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            InvestmentWorkRequest iwr = (InvestmentWorkRequest) tblCustomer.getValueAt(selectedRow, 1);
            if (iwr.getReceiver() == null) {
                int reply = JOptionPane.showConfirmDialog(null, "Assign this request to you and procced?", "Question", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (reply == 0) {
                    iwr.setReceiver(account);
                } else {
                    return;
                }
            }
            TotalCustomerInvestmentJPanel panel = new TotalCustomerInvestmentJPanel(serveCustomerContainer, iwr, enterprise);
            serveCustomerContainer.add("TotalCustomerInvestmentJPanel", panel);
            CardLayout cardLayout = (CardLayout) serveCustomerContainer.getLayout();
            cardLayout.next(serveCustomerContainer);
        }

    }//GEN-LAST:event_btnServeCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables
}
